include: package:very_good_analysis/analysis_options.11.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/generated/**"
    - build/**
    - android/**
    - ios/**
    - web/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
